apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-demo-dev
resources:
  - namespace.yaml
  - ../../base

replicas:
  - name: ci-demo
    count: 1

patches:
  - target:
      kind: Deployment
      name: ci-demo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "dev"

images:
  - name: ghcr.io/aftab-devloper/ci-demo
    newTag: 38b95965fc109d68244acb7407c727392cbbf42b
